# Generated by Django 6.0.5 on 2026-06-04 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_alter_projectboq_options_and_more'),
        ('projects', '0002_alter_customerproject_options_and_more'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storecategory',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterModelOptions(
            name='storeitem',
            options={'ordering': ['category__category_name', 'item_description']},
        ),
        migrations.AlterModelOptions(
            name='storetransaction',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='storetransaction',
            old_name='invoice_pdf',
            new_name='invoice_file',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='opening_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='amc_customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='boq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_transactions', to='boq.projectboq'),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='is_stock_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_transactions', to='projects.customerproject'),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='service_customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='stock_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='stock_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='warranty_customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='unit',
            field=models.CharField(choices=[('NOS', 'Nos'), ('MTR', 'Meter'), ('RFT', 'Rft'), ('MTR_AND_RFT', 'MTR and RFT'), ('KG', 'Kg'), ('PKT', 'Packet'), ('NOS_PKT', 'Nos / Packet'), ('LTR', 'Liter'), ('SQMTR', 'Sq. Meter'), ('ROLL', 'Roll'), ('BOX', 'Box'), ('COIL', 'Coil')], default='NOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='purpose',
            field=models.CharField(choices=[('PROJECT', 'Project Work'), ('AMC', 'AMC Work'), ('WARRANTY', 'Warranty Work'), ('SERVICE', 'Service Work'), ('PURCHASE', 'Purchase'), ('STORE', 'Store Adjustment'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RETURN', 'Material Return'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20),
        ),
    ]
