# Generated by Django 6.0.5 on 2026-06-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_storecategory_options_alter_storeitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='alert_percentage',
            field=models.DecimalField(decimal_places=2, default=85, help_text='Alert when stock is 85% used from opening stock.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
