# Generated by Django 4.2.29 on 2026-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_storecategory_id_alter_storeitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='AC unit serial number (if applicable).', max_length=100, null=True),
        ),
    ]
