# Generated by Django 6.0.6 on 2026-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storeitem_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='is_vrv',
            field=models.BooleanField(default=False, help_text='Check if this item is VRV type. Leave unchecked for Non-VRV.'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
