# Generated by Django 4.2.29 on 2026-06-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_issue', '0005_materialissueitem_return_stock_transaction_and_more'),
        ('store', '0006_add_is_vrv_to_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransaction',
            name='material_issue_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_transactions', to='material_issue.materialissueitem'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RETURN', 'Material Return'), ('SCRAP', 'Scrap'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20),
        ),
    ]
