# Generated by Django 4.2.29 on 2026-07-08 06:52

from django.db import migrations, models


def clear_non_copper_pipe_type_flags(apps, schema_editor):
    StoreItem = apps.get_model("store", "StoreItem")
    StoreItem.objects.exclude(
        item_description__icontains="copper pipe"
    ).update(
        is_vrv=False,
        is_non_vrv=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_merge_store_0010_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='is_non_vrv',
            field=models.BooleanField(default=False, help_text='Check if this item is Non-VRV type.'),
        ),
        migrations.RunPython(clear_non_copper_pipe_type_flags, migrations.RunPython.noop),
    ]
