# Generated by Django 4.2.29 on 2026-07-21 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_customerproject_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0008_alter_customer_id_alter_customerserviceschedule_id'),
        ('material_issue', '0008_alter_materialissue_project'),
        ('store', '0013_restore_all_item_type_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('INSTALLED', 'Installed'), ('RETURNED', 'Returned')], default='SCHEDULED', max_length=20)),
                ('warranty_registered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_jobs', to='customers.customer')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('current_status', models.CharField(choices=[('IN_WAREHOUSE', 'In Warehouse'), ('DISPATCHED', 'Dispatched'), ('WITH_INSTALLATION_TEAM', 'With Installation Team'), ('INSTALLED', 'Installed'), ('RETURNED_TO_WAREHOUSE', 'Returned to Warehouse'), ('DAMAGED', 'Marked Damaged'), ('MISSING', 'Marked Missing')], default='IN_WAREHOUSE', max_length=40)),
                ('condition_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_inventory_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['store_item__item_description', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('warehouse_name', models.CharField(default='Main Warehouse', max_length=160)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['warehouse_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=160)),
                ('product', models.CharField(max_length=220)),
                ('install_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_registration', to='store.installationjob')),
            ],
            options={
                'ordering': ['-install_date'],
            },
        ),
        migrations.CreateModel(
            name='UnitStatusEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_WAREHOUSE', 'In Warehouse'), ('DISPATCHED', 'Dispatched'), ('WITH_INSTALLATION_TEAM', 'With Installation Team'), ('INSTALLED', 'Installed'), ('RETURNED_TO_WAREHOUSE', 'Returned to Warehouse'), ('DAMAGED', 'Marked Damaged'), ('MISSING', 'Marked Missing')], max_length=40)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='unit_status_photos/')),
                ('condition_note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_status_events', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='store.inventoryunit')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_events', to='store.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScrapReturnRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_reference', models.CharField(blank=True, max_length=220, null=True)),
                ('complaint_or_job_reference', models.CharField(blank=True, max_length=220, null=True)),
                ('item_name', models.CharField(max_length=220)),
                ('quantity_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condition', models.CharField(choices=[('SCRAP', 'Scrap'), ('REUSABLE', 'Reusable'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='SCRAP', max_length=20)),
                ('approx_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_return_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('WAIVED', 'Waived'), ('DEDUCTED', 'Deducted From Technician'), ('APPROVED_LOSS', 'Approved Loss')], default='PENDING', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scrap_return_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scrap_return_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_return_records', to='customers.customer')),
                ('material_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_return_records', to='material_issue.materialissue')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_return_records', to='projects.customerproject')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_return_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScrapReturnEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('PARTIAL_RETURN_LOGGED', 'Partial Return Logged'), ('FULLY_RETURNED', 'Fully Returned'), ('MARKED_LOST', 'Marked Lost'), ('MARKED_WAIVED', 'Marked Waived'), ('DEDUCTED_FROM_TECHNICIAN', 'Deducted From Technician'), ('APPROVED_LOSS', 'Approved Loss'), ('REMARK_ADDED', 'Remark Added')], max_length=40)),
                ('quantity_logged', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='scrap_return_photos/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_return_events', to=settings.AUTH_USER_MODEL)),
                ('scrap_return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='store.scrapreturnrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='store.zone'),
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_units', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='store_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_units', to='store.storeitem'),
        ),
        migrations.AddField(
            model_name='installationjob',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_jobs', to='store.inventoryunit'),
        ),
    ]
