# Generated by Django 6.0.5 on 2026-06-04 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_options'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerproject',
            options={'ordering': ['-id'], 'verbose_name': 'Customer Project', 'verbose_name_plural': 'Customer Projects'},
        ),
        migrations.RemoveField(
            model_name='customerproject',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerproject',
            name='extra_note',
        ),
        migrations.AddField(
            model_name='customerproject',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='material_collection_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='material_consumed_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='project_stage_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='project_status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('ONGOING', 'Ongoing'), ('MATERIAL_REQUIRED', 'Material Required'), ('MATERIAL_ISSUED', 'Material Issued'), ('INSTALLATION', 'Installation'), ('TESTING', 'Testing'), ('HOLD', 'Hold'), ('COMMISSIONED', 'Commissioned'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=30),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='project_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='site_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='site_name',
            field=models.CharField(default='New Project Site', max_length=200),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='capacity_unit',
            field=models.CharField(choices=[('TR', 'TR'), ('HP', 'HP')], default='TR', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='capacity_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='location',
            field=models.CharField(blank=True, default='Muzaffarpur', max_length=250, null=True),
        ),
    ]
