# Generated by Django 4.2.29 on 2026-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_customerproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
