# Generated by Django 4.2.29 on 2026-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_insurance_dates_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
