# Generated by Django 4.2.29 on 2026-07-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_customerproject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='location',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
