# Generated by Django 6.0.5 on 2026-06-04 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_alter_projectboq_options_and_more'),
        ('material_issue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialissue',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='materialissueitem',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='materialissue',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='materialissueitem',
            old_name='issue',
            new_name='material_issue',
        ),
        migrations.RemoveField(
            model_name='materialissue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='materialissue',
            name='site_location',
        ),
        migrations.RemoveField(
            model_name='materialissueitem',
            name='alert_message',
        ),
        migrations.RemoveField(
            model_name='materialissueitem',
            name='is_exceeded',
        ),
        migrations.RemoveField(
            model_name='materialissueitem',
            name='is_new_boq_item',
        ),
        migrations.RemoveField(
            model_name='materialissueitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='materialissue',
            name='issue_file',
            field=models.FileField(blank=True, null=True, upload_to='material_issue_files/'),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='received_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='site_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIAL_RETURN', 'Partial Return'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='boq_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issue_items', to='boq.projectboqitem'),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='consumed_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='issued_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='issued_to',
            field=models.CharField(default='Site Engineer', max_length=200),
        ),
        migrations.AlterField(
            model_name='materialissueitem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
