# Generated by Django 6.0.5 on 2026-06-04 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_issue', '0002_alter_materialissue_options_and_more'),
        ('store', '0002_alter_storecategory_options_alter_storeitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialissue',
            name='site_note',
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='is_stock_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='stock_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issue_items', to='store.storetransaction'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
