# Generated by Django 4.2.29 on 2026-06-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_is_vrv_to_storeitem'),
        ('material_issue', '0004_alter_materialissue_id_alter_materialissueitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissueitem',
            name='return_stock_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issue_return_items', to='store.storetransaction'),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='scrap_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='scrap_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='scrap_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='scrap_stock_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issue_scrap_items', to='store.storetransaction'),
        ),
    ]
