# Generated by Django 4.2.29 on 2026-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_issue', '0005_materialissueitem_return_stock_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissue',
            name='heading',
            field=models.CharField(default='Material Issue', max_length=250),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='unused_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
