# Generated by Django 4.2.29 on 2026-07-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_customerproject_id'),
        ('material_issue', '0007_merge_unused_into_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialissue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to='projects.customerproject'),
        ),
    ]
