# Generated by Django 6.0.5 on 2026-06-04 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectboq',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='projectboq',
            old_name='description',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='projectboq',
            name='boq_date',
        ),
        migrations.RemoveField(
            model_name='projectboq',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='projectboq',
            name='quotation_number',
        ),
        migrations.AddField(
            model_name='projectboq',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectboq',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_boqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectboq',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='projectboq',
            name='title',
            field=models.CharField(default='Project BOQ', max_length=200),
        ),
        migrations.AddField(
            model_name='projectboq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectboq',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_boqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectBOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boq.projectboq')),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_boq_items', to='store.storeitem')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('boq', 'store_item')},
            },
        ),
        migrations.DeleteModel(
            name='BOQItem',
        ),
    ]
