# Generated by Django 6.0.5 on 2026-06-04 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_alter_projectboq_options_and_more'),
        ('store', '0002_alter_storecategory_options_alter_storeitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboqitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectboq',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectboq',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectboqitem',
            name='store_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='store.storeitem'),
        ),
    ]
