# Generated by Django 6.0.6 on 2026-06-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0004_alter_projectboq_id_alter_projectboqitem_id'),
        ('projects', '0004_add_insurance_dates_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectboq',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to='projects.customerproject'),
        ),
        migrations.AlterField(
            model_name='projectboqitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
