# Generated by Django 6.0.5 on 2026-05-26 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('complaint_date', models.DateField()),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('AMC', 'AMC'), ('WARRANTY', 'Warranty'), ('PAID', 'Paid Service'), ('GENERAL', 'General Complaint')], max_length=20)),
                ('nature_of_complaint', models.TextField()),
                ('technician_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('HOLD', 'Hold'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('service_completed_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_complaints', to='customers.customer')),
            ],
        ),
    ]
