# Generated by Django 6.0.5 on 2026-05-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecomplaint',
            name='service_type',
        ),
    ]
