# Generated by Django 4.2.29 on 2026-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_servicecomplaint_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecomplaint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
