# Generated by Django 6.0.5 on 2026-05-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_category',
            field=models.CharField(choices=[('GENERAL', 'General Customer'), ('WARRANTY', 'Warranty Customer'), ('AMC', 'AMC Customer')], default='GENERAL', max_length=20),
        ),
    ]
