# Generated by Django 6.0.5 on 2026-06-03 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_is_active_customer_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('WARRANTY', 'Warranty Service'), ('AMC', 'AMC Service')], max_length=20)),
                ('service_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='customers.customer')),
            ],
            options={
                'ordering': ['service_date'],
                'unique_together': {('customer', 'service_type', 'service_date')},
            },
        ),
    ]
