# Generated by Django 6.0.5 on 2026-06-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_amc_end_date_customer_amc_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
    ]
