# Generated by Django 6.0.5 on 2026-06-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerserviceschedule',
            name='complaint_register',
            field=models.FileField(blank=True, null=True, upload_to='complaint_registers/'),
        ),
    ]
