# Generated by Django 6.0.6 on 2026-06-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerserviceschedule_complaint_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerserviceschedule',
            name='complaint_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerserviceschedule',
            name='complaint_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerserviceschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
