# Generated by Django 6.0.5 on 2026-06-12 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_customerserviceschedule_complaint_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('site_type', models.CharField(choices=[('WARRANTY', 'Warranty Site'), ('AMC', 'AMC Site'), ('GENERAL', 'General Site')], default='GENERAL', max_length=20)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('no_of_technicians', models.PositiveIntegerField(default=1)),
                ('complaint_title', models.CharField(max_length=200)),
                ('complaint_description', models.TextField(blank=True, null=True)),
                ('work_done', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PARTIAL', 'Partial Work')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.customer')),
            ],
            options={
                'ordering': ['-visit_date', '-id'],
            },
        ),
    ]
