# Generated by Django 6.0.5 on 2026-05-27 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amc_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('services_per_year', models.PositiveIntegerField(default=4)),
                ('service_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], default='QUARTERLY', max_length=20)),
                ('technician_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('HOLD', 'Hold'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_contracts', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AMCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('visit_date', models.DateField()),
                ('technician_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('work_done', models.TextField(blank=True, null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='amc.amccontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
