# Generated by Django 6.0.5 on 2026-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amccontract',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='amcvisit',
            options={'ordering': ['-visit_date', '-id']},
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
